FileName:
  Exclude:
    - local-bluepill

Lint/HandleExceptions:
  Exclude:
    - bin/bluepill
    - lib/bluepill/application.rb
    - lib/bluepill/process_journal.rb
    - lib/bluepill/system.rb
    - local-bluepill
    - spec/spec_helper.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  CountComments: false
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Enabled: false

Metrics/ModuleLength:
  CountComments: false
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Style/SpecialGlobalVars:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/ClassVars:
  Exclude:
    - lib/bluepill/dsl/process_factory.rb

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    map!:     'collect!'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/GuardClause:
  Exclude:
    - lib/bluepill/dsl/process_factory.rb

Style/MultilineOperationIndentation:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'
